// @ts-nocheck
// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Symbol = {__proto__:null,wire:42, meta:44, define:46, screen:48, repeat:50, box:52, card:54, section:56, header:58, footer:60, nav:62, form:64, list:66, scroll:68, group:70, text:72, button:74, input:76, image:78, icon:80, divider:82, avatar:84, badge:86, datepicker:88, metric:90, chart:92, progress:94, skeleton:96, tabs:98, tab:100, breadcrumb:102, crumb:104, tooltip:106, toast:108, empty:110, modal:112, drawer:114, dropdown:116, popover:118}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!vQYQPOOOnQPO'#CaOOQO'#Cg'#CgOOQO'#Cp'#CpOOQO'#Cl'#ClQYQPOOOOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cf'#CfO$^QPO'#CbO$eQPO,58{OOQO-E6j-E6jO$jQPO,58|OOQO1G.g1G.g",
  stateData: "$v~OcOSPOS~OSPOWQO[QO]QO^QO_QO~OWXOeUOfUOgUOhUOiUOjVOkVOlVOmVOnVOoVOpVOqVOrVOsVOtVOuVOvVOwVOxVOyVOzVO{VO|VO}VO!OVO!PVO!QVO!RVO!SVO!TVO!UVO!VVO!WVO!XVO!YWO!ZWO![WO!]WO~ORUX~PYOR]O~ORUa~PYO^_W_~",
  goto: "!SePPPPPfloPoofPPPPrPPP|XROTX[RYPRXPQTOSZT[R[XXSOTX[",
  nodeNames: "⚠ Comment Document ) ( List ListContent FormKeyword Symbol ElementKeyword OverlayKeyword Atom String Number Keyword ParamRef",
  maxTerm: 59,
  nodeProps: [
    ["openedBy", 3,"("],
    ["closedBy", 4,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "'Z~R_XY!QYZ!Q]^!Qpq!Qrs!ctu$Pxy$qyz$v}!O${!Q![%R![!]%l!]!^&^!c!}&u#R#S&u#T#o&u~!VSc~XY!QYZ!Q]^!Qpq!Q~!fVOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y<%lO!c~#QO[~~#TRO;'S!c;'S;=`#^;=`O!c~#aWOr!crs!{s#O!c#O#P#Q#P;'S!c;'S;=`#y;=`<%l!c<%lO!c~#|P;=`<%l!c~$SR!c!}$]#R#S$]#T#o$]~$bT_~}!O$]!Q![$]!c!}$]#R#S$]#T#o$]~$vOS~~${OR~~%OP!Q![%R~%WQ]~!O!P%^!Q![%R~%aP!Q![%d~%iP]~!Q![%d~%oR!c!}%x#R#S%x#T#o%x~%}T^~}!O%x!Q![%x!c!}%x#R#S%x#T#o%x~&cSP~OY&^Z;'S&^;'S;=`&o<%lO&^~&rP;=`<%l&^~&zTW~}!O&u!Q![&u!c!}&u#R#S&u#T#o&u",
  tokenizers: [0],
  topRules: {"Document":[0,2]},
  specialized: [{term: 8, get: (value) => spec_Symbol[value] || -1}],
  tokenPrec: 171
})
