// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Comment = 1,
  Document = 2,
  List = 5,
  ListContent = 6,
  FormKeyword = 7,
  Symbol = 8,
  ElementKeyword = 9,
  OverlayKeyword = 10,
  Atom = 11,
  String = 12,
  Number = 13,
  Keyword = 14,
  ParamRef = 15
